### ISSUE TITLE
Atraer desarrolladores

### ISSUE THREAD

**Issue by iblancasa** [github-users-grx/github-users-grx.github.io#7]
¿Cómo pensáis que podríamos atraer gente? Me refiero a dar esto a conocer y eso para que la gente venga cuando se hagan quedadas...

A mí se me ha ocurrido que podríamos crear un grupo aquí:
http://www.meetup.com/

**Comment by juanAFernandez** [comment]
Buena idea, también está [geokeda](http://geokeda.es/), hecha entre otros por un profesor de la escuela :)

**Comment by germaaan** [comment]
Estaría bastante interesante, pero el problema es que fuera de redes sociales es bastante difícil conectar con la gente.

**Comment by JJ** [comment]
meetup es una buena idea, aunque también Github es una red social y hasta
ahora los mensajes aquí han funcionado bastante bien

El 2 de junio de 2015, 1:03, German Martinez <notifications@github.com>
escribió:

> Estaría bastante interesante, pero el problema es que fuera de redes
> sociales es bastante difícil conectar con la gente.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github-users-grx/github-users-grx.github.io/issues/7#issuecomment-107742154>
> .
>



-- 
JJ

**Comment by iblancasa** [comment]
Si no digo de trasladar.
Seguimos organizando todo aquí, pero abrir alguna cuenta para que sea más
fácil encontrarnos (y ponemos un enlace aquí)

**Comment by germaaan** [comment]
Claro, eso mismo, por aquí los que estamos ya lo sabemos, sería cosa de llegar a más gente. La cosa es encontrar gente que esté interesada, xD

**Comment by stringparser** [comment]
Seguir programando en proyectos propios etc como este creo que es la mejor manera de conocer gente. Mira lo que lió @JJ en su día que sigue hasta hoy :).

**Comment by ivanortegaalba** [comment]
@ccamposfuentes y yo conocimos a mucha gente en la DrupalCamp de este año, en Jeréz. De hecho, dos de los mejores que conocimos en la DrupalCamp son de Granada. Son @juanolalla y @capynet, y les conté el Gitmeetup que tenemos montado. Ellos están interesados en participar, incluso de montar algo así como un "DrupalMeetup" para atraer a drupaleros y reforzar el grupo local de Granada. Son muy "pros" y estaría de escándalo contar con ellos para nuestras reuniones.

**Comment by juanolalla** [comment]
¡Hola! Gracias @ivanortegaalba por descubrirme este grupo. Contad conmigo para todo lo que huela a software libre, frikeo y cervecismo.

**Comment by capynet** [comment]
Hola @ivanortegaalba y a todos :)
gracias por la introducción. Si señor!, con Ivan y Carlos nos lo hemos pasado muy bien en la DrupalCamp de este año, y si dios quiere la próxima va a ser en Granada (shhhhh, de momento nada confirmado).

Ya cuando queden avisen que yo trato de ir. No voy a hablar por los demás porque no se su disponibilidad.

Ah, una cosa. Para las quedadas que hacemos de drupal ("Drupal & beers") usamos meetup y es bastante cómodo para todos.

Saludos!

**Comment by iblancasa** [comment]
Hola:

Israel te ha invitado a unirte a la Copa universitaria de Dropbox. La Copa universitaria te permite unirte a tus compañeros para conseguir hasta 25 GB de espacio de Dropbox gratis durante dos años.

Para conseguir espacio, solo tienes que invitar a amigos y utilizar Dropbox para compartir, colaborar y trabajar.

¡Únete a la Copa universitaria![2]

Ten en cuenta que, para participar, debes ser un alumno inscrito actualmente en un centro de enseñanza superior. Más información acerca de la Copa universitaria[3]

¡Disfruta de Dropbox!


 
 Trabaja en equipo, gana en equipo.

____________________________________________________
Si prefieres no recibir invitaciones de Dropbox, visita este enlace[4].
Dropbox, Inc., PO Box 77767, San Francisco, California 94107

[1]: https://www.dropbox.com/l/MYhnc2at0xmtLYQ4T9qplH/campuscup?text=1
[2]: https://www.dropbox.com/l/CTwyAEUivx2Wp1GmmJlhLr/campuscup?text=1
[3]: https://www.dropbox.com/l/WR4x8wWRnifaKxA06wjdYj/help/9131?text=1
[4]: https://www.dropbox.com/l/Lau3tmlmTAFH5vLICWnlyz?text=1

**Comment by JJ** [comment]
Habría que usar meetup también...

**Comment by iblancasa** [comment]
Ay... Eso lo dije yo y no gustó. Además (no lo sabía entonces) pero para crear un grupo ahí hay que pagar (me ha dicho vente con cosas ahí… no he bicheado)

**Comment by JJ** [comment]
Pues cerrando...
